name: Auto-Merge Stage into Main

on:
  push:
    branches:
      - stage

jobs:
  merge-stage-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage branch
        uses: actions/checkout@v3
        with:
          ref: stage

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Switch to main branch
        run: |
          git checkout main || git checkout -b main
          git pull origin main || echo "No main branch history yet"

      - name: Merge stage into main
        run: |
          git merge stage --no-ff --allow-unrelated-histories -m "Auto-merge stage into main"

      - name: Push changes to main branch
        run: git push origin main
